### ISSUE TITLE
Distant edge of map is revealed when travelling near a map edge

### ISSUE THREAD

**Issue by zachgrow** [zachgrow/frupal-game#27]
When moving along one edge of the map, the opposite edge of the map's tiles are revealed as if the player were standing next to them. This would make sense if the map wrapped around its edges for player movement, but since it doesn't, this behavior is therefore a bug.

I think the GameMap::updateMap() method needs some kind of bounds checking. Right now it simply calculates the nearest tiles the player can see, which doesn't take into account the way that the mapArray is indexed.

**Comment by daemon29** [comment]
Fixed
