### ISSUE TITLE
Vendors are writing their feedback messages to the terminal

### ISSUE THREAD

**Issue by zachgrow** [zachgrow/frupal-game#28]
The vendors currently use the terminal that the game was started from to communicate with the player. We can't eliminate this entirely, because the terminal is necessary to let the player respond to the vendor, but it's not very obvious that this is happening. Therefore, I think it's probably easiest to just let the player know they need to switch to the terminal window. Something like: 
`The vendor waves you over.`
`(Use the terminal to respond.)`
would be more than sufficient.

The Event class has two functions that enable access to the in-game messagelog: a simple method to get the message log pointer, called `setMsgLogPtr(...)', and another called `(*writeMsg)(const string&)` which is the function that is used to send the messages to the GUI. Please see the code for those functions for examples of how to implement this in the Vendor class.

**Comment by csotello** [comment]
Added terminal messages before vendor action is called in the game loop to keep it from displaying multiple times.
