### ISSUE TITLE
Player.hpp has no header guards

### ISSUE THREAD

**Issue by zachgrow** [zachgrow/frupal-game#4]
As of this writing, I cannot compile from master branch because the dependencies in player.hpp are being included more than once. I think player.hpp had a header guard but I'm not sure what happened to it. Please add the following lines to the top and bottom of the header file:

#ifndef FRUPALGAME_SRC_PLAYER_HPP_INCLUDED
#define FRUPALGAME_SRC_PLAYER_HPP_INCLUDED

...

#endif //FRUPALGAME_SRC_PLAYER_HPP_INCLUDED

**Comment by csotello** [comment]
Thanks for the report, I guess I accidentally undid the header guards. They have been added.
